[build]
  publish = "_site"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NETLIFY_SITE_URL = "https://apex-flow.netlify.app"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
